clear all
time = [];
a = 0 : 0.1 :100;
for k = 1 : length(a) 
     set_param('ControlTestModel/Plant','x00',num2str(a(k)));   
     %set_param('ControlTestModel/FixedTime','th0',num2str(a(k))); 
     simOut = sim('ControlTestModel',...
    'StopTime', '30', ... 
    'ZeroCross','on', ...
    'SaveTime','on','TimeSaveName','tout', ...
    'SaveState','on','StateSaveName','xoutNew',...
    'SaveOutput','on','OutputSaveName','youtNew',...
    'SignalLogging','on','SignalLoggingName','logsout');  
     ctime=simOut.get('ctime').Data(3000);
     set_param('ControlTestModel', 'SimulationCommand', 'stop');  %½áÊø·ÂÕæ
     time(k) = ctime;
end
plot(a, time)
